import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.scss";
import { Providers } from "./providers";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Mainstack",
  description: "Generated by create next app",
};

const Degular = localFont({
  src: [
    {
      path: 'DegularDisplay-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Degular.className}>
        <Header />
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
